"""Constants, language registries, and clean SVG visual tokens."""

SUPPORTED_LANGUAGES = {
    "Auto Detect": "auto",
    "English": "en",
    "Spanish": "es",
    "French": "fr",
    "German": "de",
    "Italian": "it",
    "Portuguese": "pt",
    "Russian": "ru",
    "Hindi": "hi",
    "Telugu": "te",
    "Tamil": "ta",
    "Bengali": "bn",
    "Marathi": "mr",
    "Gujarati": "gu",
    "Kannada": "kn",
    "Malayalam": "ml",
    "Punjabi": "pa",
    "Urdu": "ur",
    "Chinese (Simplified)": "zh-CN",
    "Chinese (Traditional)": "zh-TW",
    "Japanese": "ja",
    "Korean": "ko",
    "Arabic": "ar",
    "Turkish": "tr",
    "Dutch": "nl",
    "Polish": "pl",
    "Swedish": "sv",
    "Norwegian": "no",
    "Danish": "da",
    "Finnish": "fi",
    "Greek": "el",
    "Hebrew": "he",
    "Indonesian": "id",
    "Thai": "th",
    "Vietnamese": "vi",
    "Czech": "cs",
    "Hungarian": "hu",
    "Romanian": "ro",
    "Ukrainian": "uk",
    "Persian": "fa",
}

MYMEMORY_LANG_MAP = {
    "English": "english",
    "Spanish": "spanish",
    "French": "french",
    "German": "german",
    "Italian": "italian",
    "Portuguese": "portuguese",
    "Russian": "russian",
    "Hindi": "hindi",
    "Telugu": "telugu",
    "Tamil": "tamil india",
    "Bengali": "bengali",
    "Marathi": "marathi",
    "Gujarati": "gujarati",
    "Kannada": "kannada",
    "Malayalam": "malayalam",
    "Punjabi": "punjabi",
    "Urdu": "urdu",
    "Chinese (Simplified)": "chinese simplified",
    "Chinese (Traditional)": "chinese traditional",
    "Japanese": "japanese",
    "Korean": "korean",
    "Arabic": "arabic",
    "Turkish": "turkish",
    "Dutch": "dutch",
    "Polish": "polish",
    "Swedish": "swedish",
    "Norwegian": "norwegian bokmål",
    "Danish": "danish",
    "Finnish": "finnish",
    "Greek": "greek",
    "Hebrew": "hebrew",
    "Indonesian": "indonesian",
    "Thai": "thai",
    "Vietnamese": "vietnamese",
    "Czech": "czech",
    "Hungarian": "hungarian",
    "Romanian": "romanian",
    "Ukrainian": "ukrainian",
    "Persian": "persian",
}

POPULAR_LANGUAGES = [
    "English",
    "Spanish",
    "French",
    "German",
    "Hindi",
    "Telugu",
    "Japanese",
    "Chinese (Simplified)",
    "Arabic",
    "Russian",
]

SVG_ICONS = {
    "swap": """<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m16 3 4 4-4 4"/><path d="M20 7H4"/><path d="m8 21-4-4 4-4"/><path d="M4 17h16"/></svg>""",
    "copy": """<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>""",
    "speaker": """<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><path d="M15.54 8.46a5 5 0 0 1 0 7.07"/><path d="M19.07 4.93a10 10 0 0 1 0 14.14"/></svg>""",
    "download": """<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>""",
    "trash": """<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/></svg>""",
    "check": """<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#10b981" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>""",
}
